<a href="https://colab.research.google.com/github/Bahar-karamzadeh/PyTorch-Tensor-Operations/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensor Operations


### Essential PyTorch Tensor Functions

This notebook provides a brief introduction to PyTorch and demonstrates several commonly used PyTorch tensor functions. What is PyTorch and What are Tensors? PyTorch is an open-source machine learning library widely used for numerical computation and deep learning. Tensors are the core data structure in PyTorch, and understanding basic tensor operations is essential for working with data analysis and machine learning tasks.

The following tensor functions are demonstrated in this notebook:

- `torch.manual_seed`
- `torch.zeros`
- `torch.bernoulli`
- `torch.reshape`
- `torch.cat`

In [1]:
# Import torch and other required modules
import torch





## 1. torch.manual_seed

**Description of what it does:**  
Sets the random seed so that random tensor generation is reproducible.

**Why it is useful in Deep learning?**  
Ensures the same results are obtained every time the code is run.


In [2]:
# Working Example 1
torch.manual_seed(0)
torch.rand(3)

tensor([0.4963, 0.7682, 0.0885])

This example fixes the random seed so the generated random numbers are reproducible.






In [3]:
#  working Example 2
torch.manual_seed(42)
torch.rand(2, 2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

This example uses a different seed value and generates a tensor with a different shape, showing that the seed controls reproducibility regardless of tensor size.


In [5]:
# Failing Example
torch.manual_seed("seed")


ValueError: invalid literal for int() with base 10: 'seed'

This example fails because `torch.manual_seed` only accepts an integer value.


**When to use:**  
Use `torch.manual_seed` whenever you need reproducible results, such as during experiments, debugging, or when sharing code for assignments or research.


## 2. torch.zeros

Creates a tensor filled with zeros.

In [6]:
#  working Example 1
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

This example creates a 2×3 tensor where all elements are zero. 2 rows and 3 columns.


In [7]:
#  working Example 2
torch.zeros (4)

tensor([0., 0., 0., 0.])

This example creates a one-dimensional tensor of length 4 filled with zeros.


In [8]:
# Failing example
torch.zeros(-1,3)

RuntimeError: zeros: Dimension size must be non-negative.

This example fails because tensor dimensions cannot be negative.


**When to use:**  
Use `torch.zeros` to initialize tensors, create placeholders, or allocate memory before filling it with computed values.


## 3. torch.bernoulli
Generates random binary values (0 or 1) based on given probabilities.

In [11]:
# Example 1 - working
p = torch.tensor([0.2,0.5,0.8])
torch.bernoulli(p)

tensor([0., 0., 1.])

This example generates binary values based on the probability assigned to each element.


In [12]:
# Example 2 - working
p = torch.rand(5)
torch.bernoulli(p)

tensor([0., 1., 0., 1., 0.])

This example uses randomly generated probabilities to produce random binary outcomes.


In [13]:
# Failing example
torch.bernoulli(torch.tensor([1.5,2.7]))

RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

This example fails because probabilities must be between 0 and 1.


**When to use:**  
Use `torch.bernoulli` when generating binary random values, such as for simulations, random masks, or probabilistic decisions.






### 4. torch.reshape
Changes the shape of a tensor without changing its data.

In [14]:
# Example 1 - working
t = torch.arange(6)
t.reshape (2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

`torch.arange(6)` creates a tensor with values `[0, 1, 2, 3, 4, 5]`.  
`reshape(2, 3)` reorganizes these values into a 2×3 tensor without changing the data.

In [15]:
# Example 2 - working

t.reshape (3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

This example reshapes the same tensor into another valid shape 3 * 2 with the same number of elements.


In [18]:
# Failing example
t.reshape(5,2)

RuntimeError: shape '[5, 2]' is invalid for input of size 6

This example fails because the new shape does not preserve the total number of elements.


**When to use:**  
Use `torch.reshape` when you need to reorganize tensor dimensions while keeping the underlying data unchanged.


## 5 . torch.cat



Concatenates tensors along an existing dimension.

In [19]:
# Example 1 - working
a = torch.tensor([[1,2]])
b = torch.tensor([[3,4]])
torch.cat((a,b), dim = 0)

tensor([[1, 2],
        [3, 4]])

We use [[ ]] to create a row (2D tensor) so tensors can be stacked row-wise using torch.cat.

This example concatenates two tensors along the first dimension.



In [20]:
# Example 2 - working
c = torch.tensor([1,2])
d = torch.tensor([3,4])
torch.cat((a,b), dim =0)

tensor([[1, 2],
        [3, 4]])

This example concatenates two one-dimensional tensors into a single tensor.


In [21]:
# Failing example
a = torch.tensor([[1, 2]])
b = torch.tensor([3, 4])
torch.cat((a, b), dim=0)


RuntimeError: Tensors must have same number of dimensions: got 2 and 1

This example fails because the tensors have incompatible shapes for concatenation.


**When to use:**  
Use `torch.cat` to combine multiple tensors along an existing dimension, such as merging datasets or concatenating batches.


## Conclusion



This notebook demonstrated five essential PyTorch tensor functions: `torch.manual_seed`, `torch.zeros`, `torch.bernoulli`, `torch.reshape`, and `torch.cat`. These functions covered key tensor operations including reproducible randomness, tensor initialization, binary random sampling, reshaping tensors, and combining tensors along a specified dimension.

Together, these operations illustrate how tensors can be created, controlled, reshaped, and combined in PyTorch. As a next step, these concepts can be extended to more advanced tensor operations such as indexing and slicing, tensor arithmetic, and matrix multiplication, which are fundamental for building machine learning and deep learning models.


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* PyTorch API Documentation: https://pytorch.org/docs/stable/torch.html
* PyTorch Beginner Tutorials :https://pytorch.org/tutorials/

In [22]:
!pip install jovian --upgrade --quiet

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 4.4 MB/s eta 0:00:00


In [23]:
import jovian

In [24]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
